image: ubuntu:latest

stages:
- pre_install
- build_jar

install:
  stage: pre_install
  script:
    - apt update
    - apt install maven
build:
  stage: build_jar
  script:
  - ls -la
  - mvn clean package
  when: always
  tags: [worker01]
