image: mugiwara.gitlab.yandexcloud.net:5050/mygroup/backend
default: 
  tags: [worker01]

stages:
  - build_jar
  - backend_run

.install_prereq:
  before_script:
    - apk add openssh
    - apk add sshpass
    
maven_pack:
  # extends: .install_prereq
  stage: build_jar
  script:
    - mvn clean package
  artifacts:
    expire_in: 1 week
    paths:
      - /builds/mygroup/backend/target/*.jar
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never

run_backend_part:
  extends: .install_prereq
  stage: backend_run
  script:
    - 'git clone https://oauth2:"$ANSIBLE_REPO_TOKEN"@mugiwara.gitlab.yandexcloud.net/mygroup/ansible.git'
    - cat $PRIVATE_KEY > /builds/mygroup/backend/ansible/id_rsa
    - chmod 600 /builds/mygroup/backend/ansible/id_rsa
    - cd /builds/mygroup/backend/ansible && ansible-playbook backend.yaml -e 'ansible_ssh_private_key_file=id_rsa' -e 'ansible_user=devuser'

    # - chmod 600 /builds/mygroup/backend/ansible/id_rsa && echo $VM_KEY > /builds/mygroup/backend/pass && export ANSIBLE_VAULT_PASSWORD_FILE=/builds/mygroup/backend/pass
    # # - cd ansible && ansible-playbook backend.yaml -e 'ansible_ssh_private_key_file=id_rsa' -e 'ansible_user=devuser' -vvv
    # - cd ansible && ansible-playbook backend.yaml -e 'ansible_password=$WORKER_PASS' -e 'ansible_user=devuser' -vvv
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never
