image: alpine:latest
default: 
  tags: [worker01]

stages:
  - build_jar
  - backend_run

.install_prereq:
  before_script:
    - apk update
    - apk add openjdk17-jre-headless
    - apk add maven
    - apk add ansible
    - apk add git
    
maven_pack:
  extends: .install_prereq
  stage: build_jar
  script:
    - mvn clean package
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never

run_backend_part:
  extends: .install_prereq
  stage: backend_run
  script:
    - echo $ANSIBLE_REPO_TOKEN
    - 'git clone https://oauth2:"$ANSIBLE_REPO_TOKEN"@mugiwara.gitlab.yandexcloud.net/mygroup/ansible.git'
    - ansible --version
    - cd Ansible && ansible-playbook backend.yaml -e ansible_password='$WORKER_PASS'
  when: manual
