image: ubuntu:latest
default: 
  tags: [worker01]



stages:
- pre_install
- build_jar

install:
  stage: pre_install
  script:
    - apt update -y
    - apt install maven -y

build:
  stage: build_jar
  script:
  - ls -la
  - mvn clean package
  when: always
  needs: 
    - install
