image: ubuntu:latest
default: 
  tags: [worker01]

stages:
  - build_jar

# .install_maven:
#   before_script:
#     - apt update -y
#     - apt install maven -y

build:
  # extends: .install_maven
  stage: build_jar
  script:
  - mvn clean package
  when: always
